apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: rook-ceph-ec-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  storageClassName: rook-ceph-ec-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
